.TH AI-RENAME-HOST "1" "February 2013" "AI-RENAME-HOST" "User Commands"
.SH NAME
ai-rename-host \- Rename a physical host before reinstall

.SH SYNOPSIS
.B "ai-rename-host [OPTION]... OLDHOST NEWHOST"

.SH DESCRIPTION
ai-rename-host is a tool to rename a physical host before reinstalling it. It will not rename a host 'live', and the host
must be immediately reinstalled after using the tool. It does not work with virtual nodes.
.LP
Apart from some of the options described below, the user has to
provide a hostname or a fully qualified domain name for the old hostname and the new hostname.
.LP
.TP
.I Effects:
.RS
.P
Host renamed in Foreman
.P
Old hostname deactivated in PuppetDB
.P
Alarms masked for both hostnames
.P
Old hostname removed from AIMS
.P
Host renamed in LANDDB
.RE
.LP
.I Prerequisites:
.TP
.B Valid Kerberos5 ticket
The user invoking the script must have a valid (existent and not expired)
Kerberos ticket in the file pointed by the environment variable KRB5CCNAME
(should be fine if you're on aiadm).
.SH OPTIONS
.TP
.B --config
Path to the config file (default /etc/ai/ai.conf).
.TP
.B -h, --help
Display usage and exit.
.LP
.I Advanced options:
.TP
The following parameters are for advanced users and debugging.
.TP
\fB\-\-rundeck-hostname\fR FQDN
FQDN of the Rundeck instance to use.
.TP
\fB\-\-rundeck-port\fR PORT
Port of the Rundeck instance to use.
.TP
\fB\-\-rundeck-timeout\fR INT
Timeout (in seconds) for Rundeck operations.
.TP
.B --dereference_alias
Dereference aliases in urls
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable debug messages.
.SH EXIT CODES
.TP
.B 0
All operations executed successfully.
.TP
.B 1
Bad command line.
.TP
.B 10
Error loading config file.

.SH EXAMPLES
.TP
.B Rename host foo1.cern.ch to foo2.cern.ch using FQDN
$ ai-rename-host foo1.cern.ch foo2.cern.ch

.TP
.B Rename host foo1.cern.ch to foo2.cern.ch using hostname
$ ai-rename-host --jfdi foo1 foo2


.SH REPORTING BUGS
If you experience any problem with this tool, please open a support
call on SNOW (Functional Element "Configuration Management").

.SH AUTHOR
Akos Hencz <akos.hencz@cern.ch>
