before_script:
  - yum install -y yum-utils
  - cd t




# Matricies not supported?
nosetests6:
  tags: 
    - docker
  image: centos:centos6
  script:
    - yum-config-manager --add-repo http://linuxsoft.cern.ch//epel/6/x86_64
    - yum-config-manager --add-repo http://linuxsoft.cern.ch/rdo/rdo-x86_64-stable/RPMS.openstack-rdo-juno-epel-6
    - yum install -y --nogpgcheck python-krbV python-requests-kerberos python-argparse python-nose python-suds python-requests
    - yum install -y --nogpgcheck python-openstackclient python-nose python-mock python-dateutil PyYAML
    - nosetests --exclude roger --exclude tbag

nosetests7:
  tags: 
    - docker
  image: centos:centos7
  script:
    - yum-config-manager --add-repo http://linuxsoft.cern.ch//epel/7/x86_64
    - yum-config-manager --add-repo http://linuxsoft.cern.ch/rdo/rdo-x86_64-stable/RPMS.openstack-rdo-juno-epel-7
    - yum install -y --nogpgcheck python-krbV python-requests-kerberos python-argparse python-nose python-suds python-requests
    - yum install -y --nogpgcheck python-openstackclient python-nose python-mock python-dateutil PyYAML
    - nosetests --exclude roger --exclude tbag



