#!/bin/bash
# This script helped to bootstrap a puppet-managed
# Foreman-enabled pet OpenStack VM. Now it's just
# a placeholder informing about the new-era's ai-bs-vm
# Authors:
#  Nacho Barrientos <nacho.barrientos@cern.ch>

# Exit codes:
#  0 success

echo "ai-bs-pet has been deprecated in favor of ai-bs-vm"
echo "run \`man ai-bs-vm\` to get started with the new tool"
exit 0
