#!/bin/bash
# This script helps to bootstrap a puppet-managed
# Foreman-enabled Openstack VM
# Authors:
#  Nacho Barrientos <nacho.barrientos@cern.ch>

# Exit codes:
#  0 success
#  1 user input failed
#  20 Host staging failed
#  30 VM creation failed
#  50 Other errors

# Notes:
# certmgr-stage will fail if you're not member of ai-admins egroup

function dieiffail {
  if [ $1 -ne 0 ]; then
    if [ ! -z $AIBS_VMUSERDATA_PATH]; then
      rm -f $AIBS_VMUSERDATA_PATH
    fi
    echo "$2";
    exit $3;
  fi
}

if [ -z $AIBS_HOSTGROUP_NAME ]; then
  echo "Hostgroup ID must be specified via AIBS_HOSTGROUP_NAME environment variable."
  echo "More info: 'man $0'. Exiting..."
  exit 1
fi

echo $AIBS_HOSTGROUP_NAME | egrep -q "([A-Za-z0-9/]+/spare|spare)$"
dieiffail $? "Hostgroup's tip must be 'spare'. Exiting" 1;

if [ -z $AIBS_SSHKEY_NAME ]; then
  echo "SSH key name must be specified via AIBS_SSHKEY_NAME environment variable."
  echo "More info: 'man $0'. Exiting..."
  exit 1
fi

AIBS_HOSTNAME=$1

echo $AIBS_HOSTNAME | egrep -q "\.cern\.ch$"
if [[ $# -ne 1 || $? -ne 0 ]]; then
  echo "A CERN-friendly FQDN must be provided as desired hostname"
  echo "Example: 'higgsbox.cern.ch'. Exiting."
  exit 1
fi

if [ -z $OS_USERNAME ]; then
  echo "No OpenStack credentials found. Please source openrc.sh."
  echo "More info: 'man $0'. Exiting..."
  exit 1
fi

AIBS_VMNAME=$(echo $AIBS_HOSTNAME | sed -e 's/.cern.ch//g')

# VM flavor
# (default: 'm1.tiny')
AIBS_VMFLAVOR_NAME=${AIBS_VMFLAVOR_NAME:-"m1.tiny"}

# VM Image
# (default: "[AI] SLC6 Server"
AIBS_VMIMAGE_NAME=${AIBS_VMIMAGE_NAME:-"SLC6 Server"}

echo "Trying to bootstrap $AIBS_HOSTNAME..."

#
# User data generation
#

echo "Preparing dynamic user data..."
AIBS_VMUSERDATA_PATH=$(mktemp)
rm $AIBS_VMUSERDATA_PATH
cp /usr/share/ai-tools/userdata/common $AIBS_VMUSERDATA_PATH
sed -i -e "s/%FOREMAN_HOSTGROUP%/$AIBS_HOSTGROUP_NAME/g" $AIBS_VMUSERDATA_PATH
sed -i -e "s/%FOREMAN_ENVIRONMENT%/$AIBS_ENVIRONMENT_NAME/g" $AIBS_VMUSERDATA_PATH
sed -i -e "s/%FOREMAN_OWNER%/$USER/g" $AIBS_VMUSERDATA_PATH
echo "Done (requested VM owner is '$USER')"

#
# Host staging
#

echo "Staging host on certmgr..."
certmgr-stage --host $AIBS_HOSTNAME

dieiffail $? "Failed to stage host. Exiting" 20;


#
# VM spawning
#

echo "Foreman is happy and host staged. Spawning VM..."
#  --meta "landb_create_vm=true"
nova boot --flavor $AIBS_VMFLAVOR_NAME --image "$AIBS_VMIMAGE_NAME" \
  --key_name $AIBS_SSHKEY_NAME \
  $([[ ! -z $AIBS_VMAVAILZONE_NAME ]] &&
    echo "--availability_zone $AIBS_VMAVAILZONE_NAME") \
  --user_data $AIBS_VMUSERDATA_PATH $AIBS_VMNAME

if [ $? -ne 0 ]; then
  echo "Failed to create VM. Deleting it from Foreman...";
  ai-foreman-cli delhost $AIBS_HOSTNAME --foreman-cookiejar $AIBS_COOKIEJAR_PATH;
  dieiffail $? "Deregistration on Foreman failed." 50
  echo "Failed to create VM. Unstaging host...";
  certmgr-stage --unstage --host $AIBS_HOSTNAME
  dieiffail $? "Unstage process failed." 50
  exit 30
fi

rm -f $AIBS_VMUSERDATA_PATH
echo "VM booting. Nothing else to do."

exit 0
