.TH AI-BS-VM "1" "October 2012" "ai-bs-vm" "User Commands"
.SH NAME
ai-bs-vm \- Command-line tool to generate Puppetized OpenStack VMs
.SH SYNOPSIS
ENVIRONMENT
.B "ai-bs-vm"
<hostname>
.SH DESCRIPTION
ai-bs-vm is a shell script that helps to create Puppet-managed Foreman-enabled OpenStack VMs.
.PP
.SH COMMAND OVERVIEW
.TP
See
https://twiki.cern.ch/twiki/bin/view/AgileInfrastructure/PupvmizeInstancesOnOpenstack
.SH EXAMPLES
.TP
AIBS_HOSTGROUP_NAME="foo/spare" AIBS_SSHKEY_NAME="my-key" ai-bs-vm higgsbox
.SH SEE ALSO
.TP
ai-kill-vm (1)
.PP
