.TH AI-BS-VM "1" "March 2013" "ai-bs-vm" "User Commands"
.SH NAME
ai-bs-vm \- Command-line tool to create Puppetized OpenStack VMs

.SH SYNOPSIS
.B "ai-bs-vm"
.B pet|cattle
\fIvmname\fR

.SH DESCRIPTION
ai-bs-vm is a shell script that helps to create Puppet-managed Foreman-enabled OpenStack VMs.
.LP
Foreman registration is performed by the VM itself when it
boots for the first time. Therefore it will show up in the selected
hostgroup \fBafter\fR the first boot. An email will be sent to the
owner of the box after a successful registration.
.LP
Current officially supported images are: SLC6 Server and SLC5 Server.
.LP
.I Prerequisites:
.TP
.B Foreman username
You must have logged into Foreman at least once \fBbefore\fR creating
your first virtual machine with the same username you're executing
this script (shell user)
.TP
.B OpenStack credentials
Your OpenStack credentials are in place (get an \fBopenrc.sh\fR from
OpenStack Horizon and source it). By doing this you will set the OpenStack
instance you want to use and the tenant for your VM. More info:
http://cern.ch/go/V7T7
.TP
.B Group membership
You are member of \fBai-admins\fR e-group (otherwise the host staging will
fail, the box won't get a host certificate and therefore Puppet won't
run)

.SH OPERATIONAL NOTES
Please note that cattle mode \fBis not available\fR at the moment.

.SH ENVIRONMENT
The behaviour of the tool can be customized by the following
environment variables:
.LP
.I Mandatory variables:
.TP
.B AIBS_HOSTGROUP_NAME
Name of the Foreman hostgroup where you want your new virtual
machine to land. It \fBmust have spare as tip\fP (e.g. "spare",
"lxbatch/spare", "mycoolhostgroup/spare"). \fBMake sure the hostgroup
exists before creating your virtual machine\fP. If it doesn't, just
create it. [string]
.LP
.I Optional variables:
.TP
.B AIBS_ENVIRONMENT_NAME
Name of the Foreman environment you want your new virtual
machine to join
[string] (defaults to "production")
.TP
.B AIBS_VMAVAILZONE_NAME
The desired availability zone for the VM
[string] (there is no default)
.TP
.B AIBS_VMFLAVOR_NAME
OpenStack flavor name of the virtual machine
[string] (defaults to "m1.small")
.TP
.B AIBS_VMIMAGE_NAME
OpenStack image name of the virtual machine
[string] (defaults to "SLC6 Server")
.TP
.B AIBS_SECURITYGROUPS_LIST
List of security groups your VM will belong to
[comma-separed list of strings] (defaults to "default")
Example: default,my-security-group
.TP
.B AIBS_SSHKEY_NAME
Name of the SSH key to login into the machine as root in case of
disaster. Use Horizon or nova keypair-add to generate a new keypair
[string]. Because of the security implications this option has, it's
strongly recommended to avoid it. Your new VM will have the Kerberos
module enabled by default, use it to configure who has root access
to the box. See http://cern.ch/go/7qW6
.LP
.I Other optional variables:
.TP
The following parameters are for advanced users and debugging.
.TP
Probably you won't ever have to use any of them.
.TP
.B AIBS_METAPARAMETERS_LIST
Space separated list of key=value pairs of metaparameters for nova boot (e.g
"key1=value1 key2=value2").
[string] (there is no default)
.TP
.B AIBS_SUSIE_HOSTNAME
Host name of the Susie service (Foreman proxy)
[string] (defaults to "aisusie.cern.ch")
.TP
.B AIBS_SUSIE_PORT
Port where Susie is listening to
[string] (defaults to "443")
.TP
.B AIBS_VMBASEUSERDATA_PATH
Path to the template to generate the user data
of the virtual machine.
[string] (defaults to "/usr/share/ai-tools/userdata/common")

.SH EXAMPLES
.TP
.B Create a pet VM with default VM parameters and register it in hostgroup "foo/spare":
AIBS_HOSTGROUP_NAME="foo/spare" ai-bs-vm pet higgsbox

.TP
.B Same but with custom environment:
AIBS_HOSTGROUP_NAME="foo/spare"
AIBS_ENVIRONMENT_NAME="devel" ai-bs-vm pet higgsbox

.TP
.B Now with personalized security groups, different VM flavor and SSH key:
AIBS_SECURITYGROUPS_LIST="default,my-sec-group" AIBS_HOSTGROUP_NAME="foo/spare"
AIBS_SSHKEY_NAME="my-key" AIBS_ENVIRONMENT_NAME="devel"
AIBS_VMFLAVOR_NAME="m1.large" ai-bs-vm pet higgsbox

.SH BUGS
Any problem? Open a support call on Jira
(https://its.cern.ch/jira/) project "Agile Infrastructure" and assign it
to Nacho Barrientos Arias <nacho.barrientos@cern.ch>.

.SH SEE ALSO
ai-kill-vm (1)
