.TH AI-KILL-PET "1" "October 2012" "ai-kill-pet" "User Commands"
.SH NAME
ai-kill-pet \- Command-line tool to kill pets
.SH SYNOPSIS
.B "ai-kill-pet"
<hostname>
.SH DESCRIPTION
ai-kill-pet is a shell script that helps to kill Puppet-managed Foreman-enabled pet OpenStack VMs.
.PP
.SH COMMAND OVERVIEW
.TP
See
https://twiki.cern.ch/twiki/bin/view/AgileInfrastructure/PuppetizeInstancesOnOpenstack
.SH EXAMPLES
.TP
ai-kill-pet higgsbox.cern.ch
.SH SEE ALSO
.TP
ai-bs-pet (1)
.PP
