.TH AI-KILL-VM "1" "October 2012" "ai-kill-vm" "User Commands"
.SH NAME
ai-kill-vm \- Command-line tool to kill OpenStack VMs
.SH SYNOPSIS
.B "ai-kill-vm"
<hostname>
.SH DESCRIPTION
ai-kill-vm is a shell script that helps to kill Puppet-managed Foreman-enabled OpenStack VMs.
.PP
.SH COMMAND OVERVIEW
.TP
See
https://twiki.cern.ch/twiki/bin/view/AgileInfrastructure/PuppetizeInstancesOnOpenstack
.SH EXAMPLES
.TP
ai-kill-vm higgsbox.cern.ch
.SH SEE ALSO
.TP
ai-bs-pet (1), ai-bs-vm (1)
.PP
