.TH AI-REMOTE-POWER-CONTROL "1" "July 2013" "ai-remote-power-control" "User Commands"
.SH NAME
ai-remote-power-control \- CLI to perform IPMI power operations on AI physical machines.

.SH SYNOPSIS
.B "ai-remote-power-control [OPTIONS] FQDN [FQDN ...]"

.SH DESCRIPTION
ai-remote-power-control is a command line tool to do IPMI power operations on
AI physical machines via Foreman. It features Kerberos authentication,
parallelism and optional JSON output. The default output
format is a human-readable summary with one machine per line.
.LP
Apart from some of the options described below, the user has to
provide a list of CERN-valid FQDNs (for instance, foo.cern.ch)
.LP
For Quattor-managed machines use remote-power-control instead.
.LP
.I Prerequisites:
.TP
.B Valid Kerberos5 ticket
The user invoking the script must have a valid (existent and not expired)
Kerberos ticket in the file pointed by the environment variable KRB5CCNAME.
.TP
.B Machine visibility
Only operations on machines visible for the invoking user in Foreman and 
with a valid IPMI interface will succeed.

.SH OPTIONS
.TP
\fB\-e\fR, \fB\-\-errors-only\fR
Only add to the report machines on which the requested operation failed.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display usage and exit.
.TP
\fB\-j\fR, \fB\-\-json\fR
Print a machine-readable output in JSON (see JSON OUTPUT for details).
.TP
\fB\-o\fR, \fB\-\-operation\fR OPERATION
IPMI operation to perform, defaults to "status" (see IPMI OPERATIONS).

.LP
.I Advanced options:
.TP
The following parameters are for advanced users and debugging.

.TP
\fB\-\-foreman-hostname\fR FQDN
FQDN of the Foreman instance to use (defaults to "judy.cern.ch").
.TP
\fB\-\-foreman-port\fR PORT
Port of the Foreman instance to use (defaults to 443).
.TP
\fB\-t\fR, \fB\-\-threads\fR INT
Number of concurrent IPMI operations (defaults to the number of cores, with
a maximum of twice the default value).
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable debug messages (recommended to use -t 1 too).

.SH IPMI OPERATIONS
.TP
These are currently the IPMI operations allowed by Foreman's API:
.TP
.B cycle
Turn power off, wait and then turn power on.
.TP
.B off
Turn power off without an orchestrated shutdown.
.TP
.B on
Turn power on.
.TP
.B soft
Do an OS shutdown via ACPI.
.TP
.B status
Query power status (default).

.SH EXIT CODES
.TP
.B 0
All operations executed successfully.
.TP
.B 1
Some IPMI operations have failed (see details at machine level).
.TP
.B 2
Bad command line.

.SH JSON OUTPUT
.TP
The JSON output is basically a list of dictionaries. Each dictionary 
contains the following keys:
.TP
.B fqdn
FQDN of the machine being reported.
.TP
.B success
Boolean describing if the operation was executed successfully.
.TP
.B details
In case of error (success is false) this field contains the error
message. In case of success, it ships the current IPMI state if
a status operation is invoked, otherwise it will read "Command sent".

.LP
.I Example:
.TP
[{"fqdn": "susie.cern.ch", "success": true, "details": "ON"}]
.TP
[{"fqdn": "murphy.cern.ch", "success": false, "details": "Host not in Foreman or
without an IPMI interface (VM?)"}]

.SH EXAMPLES
.TP
.B Do a 'status' operation on host higgs.cern.ch
$ ai-remote-power-control higgs.cern.ch
.br
higgs.cern.ch: ON

.TP
.B Do an 'on' operation on hosts higgs.cern.ch and gijon.cern.ch and produce JSON output
$ ai-remote-power-control -o on -j higgs.cern.ch gijon.cern.ch
.br
higgs.cern.ch: Command sent
.br
gijon.cern.ch: Error (Host not in Foreman or without an IPMI interface (VM?))

.TP
.B Do a 'cycle' operation on host geneva.cern.ch and print only errors
$ ai-remote-power-control -o cycle -e 404.cern.ch
.br
404.cern.ch: Error (Host not in Foreman or without an IPMI interface (VM?))

.LP
.I Combining it with Mcollective:

.TP
.B Do a 'cycle' operation on all the Puppet masters :)
$ mco find -T punch -F hostgroup_0=punch -F hostgroup_2=master | xargs ai-remote-power-control -o cycle

.SH BUGS
Any problem? Open a support call on Jira
(https://its.cern.ch/jira/) project "Agile Infrastructure".

.SH AUTHOR
Nacho Barrientos <nacho.barrientos@cern.ch> 

.SH SEE ALSO
remote-power-control (1), ai-foreman-cli (1)
