#!/usr/bin/python
# CERN
# IT Department
# Nacho Barrientos <nacho.barrientos@cern.ch>
# This script determines via PuppetDB the type of 
# a module passed as parameter. Return codes:
#  - 01: Error
#  - 10: Module is core or shared
#  - 11: Module is individual
#  - 12: Module is not affecting any top-level hostgroups
# May 2013

import sys
import json
import urllib
import argparse
import datetime
import logging
import requests
from requests_kerberos import HTTPKerberosAuth

CONFIG_PDB_HOST = "judy.cern.ch"
CONFIG_PDB_PORT = "9081"
CONFIG_DEFAULT_DEBUG_LEVEL = logging.ERROR
CONFIG_HTTPCONN_TIMEOUT = 500
CERN_CA_BUNDLE = "/etc/ssl/certs/CERN-bundle.pem"

def enum(**enums):
    return type('Enum', (), enums)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--module', type=str, required=True, 
        help="Concerned module name")
    parser.add_argument('--verbose', '-v', action='store_true',
        help="Enable debugging")
    parser.add_argument('--silent', '-s', action='store_true',
        help="Display only error messages")
    return parser.parse_args()

def configure_logging(args):
    level = CONFIG_DEFAULT_DEBUG_LEVEL
    format = '%(message)s'
    if args.verbose:
        level = logging.DEBUG
        format = '%(asctime)s %(levelname)s %(message)s'
    if args.silent:
        level = logging.ERROR
    logging.basicConfig(
        level = level,
        format = format)

def get_toplevel_affected_hgs(modulename):
    logging.info("Getting count of top-level hostgroups using module '%s'..." % modulename)
    modulename = "%s%s" % (modulename[0].upper(), modulename[1:].lower())

    query = """
["and",["=","name","hostgroup_0"], 
["in","certname",["extract","certname", 
["select-resources", ["and",["=", "type", "Class"],
["~","title","\\\A%s"]]]]]]
""" % modulename
    logging.debug(query)

    url = "https://%s:%s/v2/facts" % (CONFIG_PDB_HOST, CONFIG_PDB_PORT)
    params = {'query': query}
    headers = {"Accept": "application/json",
        "Content-type": "application/x-www-form-urlencoded"}

    response = requests.get(url, data=urllib.urlencode(params),
        headers=headers, auth=HTTPKerberosAuth(),
        verify=CERN_CA_BUNDLE, allow_redirects=True)
    if response.status_code == requests.codes.ok:
        output = json.loads(response.text)
        toplevel = set(map(lambda x: x['value'], output))
        hostgroups = ",".join(sorted(toplevel))
        return hostgroups
    else:
        raise Exception()

def main():
    args = parse_args()
    configure_logging(args)

    try:
        toplevel_affected_hostgroups = \
            get_toplevel_affected_hgs(args.module)
    except Exception, error:
        logging.error("Failed to get data from Puppet DB (%s)" % error)
        sys.exit(1)

    print "Affected hostgroups: %s" % toplevel_affected_hostgroups
    if len(toplevel_affected_hostgroups) > 1:
        print "More than one top-level hostgroup affected => shared"
        sys.exit(10)
    elif len(toplevel_affected_hostgroups) == 1:
        print "Only one top-level hostgroup affected => individual"
        sys.exit(11)
    else:
        print "No hostgroups are using this module"
        sys.exit(12)

if __name__ == "__main__":
    main()
