#!/bin/bash
# CERN
# IT Department
# Nacho Barrientos <nacho.barrientos@cern.ch>
# This scripts prints out the name of modules
# that are shared or core. This script must be
# invoked in the root directory of a clone of
# punch-modules.
# May 2013

CERT=$1
KEY=$2

function die {
    echo $1
    exit 1
}

function usage {
    die "$0 path_to_certificate path_to_key"
}

[[ -z $CERT ]] && usage
[[ -z $CERT ]] && usage
[[ -d "modules" ]] || die "Seems you're not inside a clone of punch-modules"
[[ -f $CERT ]] || die "Certificate not readable"
[[ -f $KEY ]] || die "Certificate key not readable"

TMP=`mktemp`
for module in `ls -1 modules`; do
    ai-rmt-module-type --cert $CERT --key $KEY --module $module &> $TMP
    [[ $? == 10 ]] && cat $TMP
done

rm $TMP
