#!/usr/bin/python
# CERN
# IT Department
# Nacho Barrientos <nacho.barrientos@cern.ch>
# This script determines via PuppetDB the type of 
# a module passed as parameter. Return codes:
#  - 01: Error
#  - 10: Module is core or shared
#  - 11: Module is individual
#  - 12: Module is not affecting any top-level hostgroups
# May 2013

import sys
import httplib
import json
import urllib
import argparse
import datetime
import logging

CONFIG_PDB_HOST = "judy.cern.ch"
CONFIG_PDB_PORT = "8081"
CONFIG_DEFAULT_DEBUG_LEVEL = logging.INFO
CONFIG_HTTPCONN_TIMEOUT = 500

def enum(**enums):
    return type('Enum', (), enums)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--cert', type=str, required=True,
        help="User certificate path")
    parser.add_argument('--key', type=str, required=True, 
        help="User certificate key")
    parser.add_argument('--module', type=str, required=True, 
        help="Concerned module name")
    parser.add_argument('--verbose', '-v', action='store_true',
        help="Enable debugging")
    parser.add_argument('--silent', '-s', action='store_true',
        help="Display only error messages")
    return parser.parse_args()

def configure_logging(args):
    level = CONFIG_DEFAULT_DEBUG_LEVEL
    format = '%(message)s'
    if args.verbose:
        level = logging.DEBUG
        format = '%(asctime)s %(levelname)s %(message)s'
    if args.silent:
        level = logging.ERROR
    logging.basicConfig(
        level = level,
        format = format)

def get_toplevel_affected_hgs_count(conn, modulename):
    logging.info("Getting count of top-level hostgroups using module '%s'..." % modulename)
    modulename = "%s%s" % (modulename[0].upper(), modulename[1:].lower())

    query = """
["and",["=","name","hostgroup_0"], 
["in","certname",["extract","certname", 
["select-resources", ["and",["=", "type", "Class"], 
["=","title","%s"]]]]]]
""" % modulename
    logging.debug(query)

    params = {'query': query}
    headers = {"Accept": "application/json",
        "Content-type": "application/x-www-form-urlencoded"}

    conn.request("GET", "/v2/facts", urllib.urlencode(params), headers)
    res = conn.getresponse()
    if res.status == httplib.OK:
        output = json.loads(res.read())
        toplevel = set(map(lambda x: x['value'], output))
        hostgroups = ",".join(sorted(toplevel))
        count = len(toplevel)
        logging.info("%s found (%s)" % (count, hostgroups))
        print hostgroups
        return count
    else:
        raise Exception()

def main():
    args = parse_args()
    configure_logging(args)
    conn = httplib.HTTPSConnection(host=CONFIG_PDB_HOST,
        port=CONFIG_PDB_PORT,
        timeout=CONFIG_HTTPCONN_TIMEOUT,
        key_file=args.key,
        cert_file=args.cert)

    try:
        toplevel_affected_hostgroups = \
            get_toplevel_affected_hgs_count(conn, args.module)
    except Exception, error:
        logging.error("Failed to get data from Puppet DB (%s)" % error)
        sys.exit(1)

    if toplevel_affected_hostgroups > 1:
        logging.info("More than one top-level hostgroup affected => shared")
        sys.exit(10)
    elif toplevel_affected_hostgroups == 1:
        logging.info("Only one top-level hostgroup affected => individual")
        sys.exit(11)
    else:
        logging.info("No hostgroups are using this module")
        sys.exit(12)

if __name__ == "__main__":
    main()
