#!/bin/bash
# This script helps to perform power operations
# on IPMI-enabled hosts via Foreman.
# Authors:
#  Nacho Barrientos <nacho.barrientos@cern.ch>
# July 2013

# Exit codes:
#  0 success
#  1 some power operations failed
#  10 bad command line
#  20 current TGT is not valid or missing
#  30 failed to obtain a SSO cookie

# TODO:
# * Verify HTTP codes
# * Consider output if the operation is 'status'

VALID_OPERATIONS=(on off soft cycle status)
FOREMAN_API_URL="https://judy.cern.ch/api"
CACERT="/etc/pki/tls/certs/CERN-bundle.pem"

function usage {
  [[ -n $1 ]] && echo $1
  echo "Usage:"
  echo "$0 <OPERATION> <FQDN>..."
  echo -e "\tOPERATION: Either of:"
  printf -- "\t\t%s\n" "${VALID_OPERATIONS[@]}"
  echo -e "\tFQDN: One or more FQDNs separed by blank"
  echo "Example: ai-remote-power-control cycle foo.cern.ch bar.cern.ch"
  echo "A valid Kerberos TGT is required for authentication"
  exit 10
}

function dieiffail {
  if [ $1 -ne 0 ]; then
    die $2 $3
  fi
}

function die {
  rm -r $AIBS_COOKIEJAR_PATH
  echo "$1";
  [[ -z $2 ]] && exit -1
  exit $2
}

[[ $# -lt 2 ]] && usage

OPERATION=$1
shift

function validate_operation {
  for valid_operation in "${VALID_OPERATIONS[@]}"
  do
    [[ "${valid_operation}" == $1 ]] && return 0
  done
  return 1
}

validate_operation $OPERATION
[[ $? -eq 1 ]] && usage "Operation $OPERATION is not valid"

#
# Verify that the user has a valid TGT
#
echo "Validating current TGT..."
klist -s
dieiffail $? "Current ticket is not valid (klist -s returned non-zero status)" 20

#
# Cookie jar
#

AIBS_COOKIEJAR_PATH=$(mktemp --tmpdir=$HOME --suffix="judy-cj-$HOSTNAME")
#echo "Getting cookie jar..."
#cern-get-sso-cookie --krb -u https://judy.cern.ch -o $AIBS_COOKIEJAR_PATH -r
#dieiffail $? "Failed to get SSO cookie (bad KRB credentials?). Exiting" 30

#
# Cookie validation
#

#FOREMANCLIOUT=$(ai-foreman-cli chkhost $AIBS_HOSTNAME --foreman-cookiejar $AIBS_COOKIEJAR_PATH 2>&1)
#echo $FOREMANCLIOUT | egrep -q ".+Bad cookie.+"
#[[ $? -eq 0 ]] && dieiffail 1 "Cookie refused. Try again and open a ticket of the problem persists." 30;

function foreman_power_operation {
  # $1: operation
  # $2: FQDN
  # Returns HTTP status code
  OPERATION=$1
  FQDN=$2
  echo "Executing '$OPERATION' on host $FQDN..."
  return "200" # FIXME
  IPMIFQDN=$(echo $FQDN | sed -e "s/\.cern\.ch/-ipmi.cern.ch/g")
  URL="$FOREMAN_API_URL/hosts/$FQDN/interfaces/$IPMIFQDN/power"
  #echo $URL # FIXME
  BODY="{"
  BODY="$BODY \"power_action\": \"$OPERATION\""
  BODY="$BODY }"
  #echo $BODY # FIXME
  HTTP_CODE=$(curl -H "Content-Type: application/json" \
    -H "Accept:application/json, version=2" \
    --cookie $AIBS_COOKIEJAR_PATH \
    -d "$BODY" -X PUT \
    --cacert $CACERT \
    -s -L -o /dev/null --write-out "%{http_code}"\
    $URL)
  return $HTTP_CODE
}

while [ ! -z $1 ]
  do
    FQDN=$1
    shift
    echo "Processing host $FQDN..."
    echo $FQDN | egrep -q "\.cern\.ch$"
    [[ $? -ne 0 ]] && echo "$FQDN is not a valid CERN FQDN. Skipping..." && continue

    foreman_power_operation $OPERATION $FQDN
    FOREMAN_HTTP_CODE=$?
    if [ $FOREMAN_HTTP_CODE == "200" ]; then
        echo "Command sent"
    elif [ $FOREMAN_HTTP_CODE == "404" ]; then
        [[ -z $FAILED_OPERATIONS ]] && FAILED_OPERATIONS="YES"
        echo "Operation failed, host not in Foreman or missing IMPI interface"
    else
        [[ -z $FAILED_OPERATIONS ]] && FAILED_OPERATIONS="YES"
        echo "Operation failed with an unexpeted HTTP status code ($FOREMAN_HTTP_CODE)"
    fi
done

rm -r $AIBS_COOKIEJAR_PATH
echo "All machines processed"
[[ ! -z $FAILED_OPERATIONS ]] && exit 1
exit 0
