#!/bin/bash
# CERN
# IT Department
# Nacho Barrientos <nacho.barrientos@cern.ch>
# This scripts prints out the name of all modules
# and the type separed by hyphen. Example:
#  sssd - shared
#  castor - individual
# May 2013

CERT=$1
KEY=$2

function die {
    echo $1
    exit 1
}

function usage {
    die "$0 path_to_certificate path_to_key"
}

[[ -z $CERT ]] && usage
[[ -z $KEY ]] && usage
[[ -d "modules" ]] || die "Seems you're not inside a clone of punch-modules"
[[ -f $CERT ]] || die "Certificate not readable"
[[ -f $KEY ]] || die "Certificate key not readable"

for module in `ls -1 modules`; do
    hostgroups=$(python ~/ai-tools/ai-rmt-module-type --cert $CERT --key $KEY --module $module -s)
    TYPE=$?
    [[ $TYPE == 10 ]] && echo "$module | shared | $hostgroups |"
    [[ $TYPE == 11 ]] && echo "$module | individual | $hostgroups |"
    [[ $TYPE == 12 ]] && echo "$module | notused | $hostgroups |"
done
