PKGNAME=ai-tools-3.19
TARFILE=$(PKGNAME).tgz

all:
	#tar cvzf $(TARFILE) --exclude-vcs --transform 's,^,$(PKGNAME)/,' *
	rm -rf /tmp/$(PKGNAME)
	mkdir /tmp/$(PKGNAME)
	cp -rv * /tmp/$(PKGNAME)/
	pwd ; ls -l
	cd /tmp ; tar --exclude .svn --exclude .git -czf $(TARFILE) $(PKGNAME)
	mv /tmp/$(TARFILE) .
	rm -rf /tmp/$(PKGNAME)

clean:
	rm $(TARFILE)
